const products = [{
      name: "QiYi Warior 3x3 S",
      price: 3.9,
      type: "3x3",
      brand: "QiYi",
      image: ".//qiyi-warrior-3x3-s.webp",
    },
    {
      name: "Shengshou Legend 3x3",
      price: 6.35,
      type: "3x3",
      brand: "Shengshou",
      image: ".//shengshou-legend-3x3.webp",
    },
    {
      name: "QiYi Mirror 3x3",
      price: 5.25,
      type: "Modificaciones 3x3",
      brand: "QiYi",
      image: "/qiyi-mirror-3x3.webp",
    },
    {
      name: "QiYi Axis 3x3",
      price: 5.25,
      type: "Modificaciones 3x3",
      brand: "QiYi",
      image: ".//qiyi-axis-3x3.webp",
    },
    {
      name: "YJ YuPo 2x2 V2M ",
      price: 6.9,
      type: "2x2",
      brand: "YJ",
      image: "/yj-yupo-2x2-v2-m.webp",
    },
    {
      name: "Lee 2x2 windmill cube",
      price: 6.35,
      type: "Modificaciones 2x2",
      brand: "Lee",
      image: "/lee-2x2-windmill-cube.webp",
    },
    {
      name: "DianSheng 8 Corner",
      price: 12.90,
      type: "Modificaciones 4x4",
      brand: "DianSheng",
      image: "/diansheng-8-corner.webp",
    },
    {
      name: "MeiLong 4x4",
      price: 5.25,
      type: "4x4",
      brand: "MeiLong",
      image: "/meilong-4x4.webp",
    },
  ];
export default products